import { SpikeDirection } from '../enums';

/*
  Sizing in grid terms:
    - 1 grid unit = 24 pixels
    - platform = 1x1 (x length)
    - spike = 1x1
    - turret = 2x2
    - blade = 2x2
  (x,y) coordinates indicate the top left cell of the object
*/

export const LEVEL_WIDTH = 42;
export const LEVEL_HEIGHT = 20;

const levels = [
  {
    startGate: { x: 1, y: 1 },
    endGate: { x: 38, y: 17 },
    platforms: [
      { x: 0, y: 4, length: 4, isVertical: false },
      { x: 7, y: 12, length: 4, isVertical: false },
      { x: 19, y: 17, length: 3, isVertical: false },
      { x: 26, y: 18, length: 2, isVertical: false },
    ],
    spikes: [
      { x: 12, y: 19, length: 4, isVertical: false, direction: SpikeDirection.UP },
      { x: 22, y: 19, length: 4, isVertical: false, direction: SpikeDirection.UP },
    ],
  },
  {
    startGate: { x: 1, y: 1 },
    endGate: { x: 38, y: 17 },
    platforms: [
      { x: 0, y: 4, length: 4, isVertical: false },
      { x: 7, y: 12, length: 4, isVertical: false },
      { x: 19, y: 17, length: 3, isVertical: false },
      { x: 26, y: 18, length: 2, isVertical: false },
    ],
    spikes: [
      { x: 0, y: 19, length: 26, isVertical: false, direction: SpikeDirection.UP },
    ],
    blades: [
      { x1: 12, y1: 16, x2: 18, y2: 9, delay: 0 },
    ],
  },
  {
    startGate: { x: 1, y: 1 },
    endGate: { x: 38, y: 17 },
    platforms: [
      { x: 0, y: 4, length: 4, isVertical: false },
      { x: 7, y: 12, length: 4, isVertical: false },
      { x: 19, y: 17, length: 3, isVertical: false },
      { x: 26, y: 18, length: 2, isVertical: false },
    ],
    spikes: [
      { x: 0, y: 19, length: 26, isVertical: false, direction: SpikeDirection.UP },
      { x: 7, y: 11, length: 1, isVertical: false, direction: SpikeDirection.UP },
      { x: 29, y: 19, length: 3, isVertical: false, direction: SpikeDirection.UP },
    ],
    blades: [
      { x1: 12, y1: 16, x2: 18, y2: 9, delay: 0 },
      { x1: 7, y1: 5, x2: 1, y2: 10, delay: 0 },
    ],
    turrets: [
      { x: 25, y: 1, startDelay: 2000 },
    ],
  },
  {
    startGate: { x: 1, y: 1 },
    endGate: { x: 38, y: 17 },
    platforms: [
      { x: 0, y: 4, length: 4, isVertical: false },
      { x: 7, y: 12, length: 4, isVertical: false },
      { x: 19, y: 17, length: 3, isVertical: false },
      { x: 26, y: 18, length: 2, isVertical: false },
      { x: 28, y: 14, length: 3, isVertical: false },
      { x: 30, y: 10, length: 4, isVertical: true },
      { x: 37, y: 15, length: 5, isVertical: false },
      { x: 31, y: 8, length: 5, isVertical: false },
    ],
    spikes: [
      { x: 0, y: 19, length: 26, isVertical: false, direction: SpikeDirection.UP },
      { x: 7, y: 11, length: 1, isVertical: false, direction: SpikeDirection.UP },
      { x: 29, y: 19, length: 3, isVertical: false, direction: SpikeDirection.UP },
    ],
    blades: [
      { x1: 12, y1: 16, x2: 18, y2: 9, delay: 0 },
      { x1: 7, y1: 5, x2: 1, y2: 10, delay: 0 },
    ],
    turrets: [
      { x: 25, y: 1, startDelay: 2000 },
    ],
    lasers: [
      { x: 39, y: 1, angle: -70, startDelay: 0 },
    ],
  },
  {
    startGate: { x: 1, y: 1 },
    endGate: { x: 38, y: 17 },
    platforms: [
      { x: 0, y: 4, length: 4, isVertical: false },
      { x: 7, y: 12, length: 4, isVertical: false },
      { x: 12, y: 17, length: 10, isVertical: false },
      { x: 28, y: 14, length: 3, isVertical: false },
      { x: 30, y: 10, length: 4, isVertical: true },
      { x: 37, y: 15, length: 5, isVertical: false },
      { x: 31, y: 8, length: 5, isVertical: false },
      { x: 11, y: 0, length: 7, isVertical: true },
      { x: 12, y: 6, length: 8, isVertical: false },
      { x: 20, y: 0, length: 7, isVertical: true },
      { x: 24, y: 14, length: 2, isVertical: false },
      { x: 25, y: 5, length: 7, isVertical: true },
      { x: 21, y: 0, length: 12, isVertical: true },
      { x: 22, y: 10, length: 1, isVertical: true },
    ],
    spikes: [
      { x: 0, y: 19, length: 32, isVertical: false, direction: SpikeDirection.UP },
      { x: 7, y: 11, length: 1, isVertical: false, direction: SpikeDirection.UP },
      { x: 41, y: 5, length: 10, isVertical: true, direction: SpikeDirection.LEFT },
    ],
    blades: [
      { x1: 13, y1: 15, x2: 18, y2: 9, delay: 1000 },
      { x1: 7, y1: 5, x2: 1, y2: 10, delay: 1000 },
      { x1: 32, y1: 1, x2: 32, y2: 6, delay: 0 },
    ],
    turrets: [
      { x: 25, y: 1, startDelay: 2000 },
      { x: 31, y: 10, startDelay: 2000 },
      { x: 9, y: 0, startDelay: 4000 },
    ],
    lasers: [
      { x: 39, y: 1, angle: -70, startDelay: 0 },
      { x: 23, y: 17, angle: 30, startDelay: 1000 },
    ],
  },
  {
    startGate: { x: 1, y: 1 },
    endGate: { x: 38, y: 17 },
    platforms: [
      { x: 0, y: 4, length: 4, isVertical: false },
      { x: 7, y: 12, length: 4, isVertical: false },
      { x: 12, y: 17, length: 10, isVertical: false },
      { x: 28, y: 14, length: 3, isVertical: false },
      { x: 30, y: 10, length: 4, isVertical: true },
      { x: 37, y: 15, length: 5, isVertical: false },
      { x: 31, y: 8, length: 5, isVertical: false },
      { x: 11, y: 0, length: 7, isVertical: true },
      { x: 12, y: 6, length: 8, isVertical: false },
      { x: 20, y: 0, length: 7, isVertical: true },
      { x: 24, y: 14, length: 2, isVertical: false },
      { x: 25, y: 5, length: 7, isVertical: true },
      { x: 21, y: 0, length: 12, isVertical: true },
      { x: 22, y: 10, length: 1, isVertical: true },
      { x: 34, y: 16, length: 4, isVertical: false },
    ],
    spikes: [
      { x: 0, y: 19, length: 32, isVertical: false, direction: SpikeDirection.UP },
      { x: 7, y: 11, length: 1, isVertical: false, direction: SpikeDirection.UP },
      { x: 41, y: 5, length: 10, isVertical: true, direction: SpikeDirection.LEFT },
      { x: 0, y: 0, length: 4, isVertical: true, direction: SpikeDirection.RIGHT },
    ],
    blades: [
      { x1: 13, y1: 15, x2: 18, y2: 9, delay: 1000 },
      { x1: 7, y1: 5, x2: 1, y2: 10, delay: 1000 },
      { x1: 32, y1: 1, x2: 32, y2: 6, delay: 0 },
    ],
    turrets: [
      { x: 25, y: 1, startDelay: 2000 },
      { x: 31, y: 10, startDelay: 2000 },
      { x: 9, y: 0, startDelay: 4000 },
      { x: 1, y: 14, startDelay: 3000 },
      { x: 28, y: 16, startDelay: 0 },
    ],
    lasers: [
      { x: 39, y: 1, angle: -70, startDelay: 0 },
      { x: 23, y: 17, angle: 30, startDelay: 1000 },
      { x: 26, y: 17, angle: 100, startDelay: 1000 },
    ],
  },

  // New set of levels
  {
    startGate: { x: 1, y: 17 },
    endGate: { x: 38, y: 1 },
    platforms: [
      { x: 36, y: 4, length: 6, isVertical: false },
      { x: 5, y: 19, length: 7, isVertical: false },
      { x: 5, y: 18, length: 7, isVertical: false },
      { x: 13, y: 19, length: 15, isVertical: false },
      { x: 13, y: 18, length: 11, isVertical: false },
      { x: 6, y: 15, length: 12, isVertical: false },
      { x: 20, y: 11, length: 6, isVertical: true },
      { x: 0, y: 14, length: 8, isVertical: false },
      { x: 7, y: 10, length: 14, isVertical: false },
      { x: 0, y: 10, length: 5, isVertical: false },
      { x: 18, y: 4, length: 6, isVertical: true },
      { x: 19, y: 4, length: 6, isVertical: true },
      { x: 20, y: 4, length: 6, isVertical: true },
      { x: 16, y: 7, length: 3, isVertical: true },
      { x: 17, y: 7, length: 3, isVertical: true },
      { x: 21, y: 16, length: 3, isVertical: false },
      { x: 23, y: 17, length: 1, isVertical: false },
      { x: 24, y: 0, length: 14, isVertical: true },
      { x: 29, y: 15, length: 1, isVertical: false },
      { x: 34, y: 11, length: 1, isVertical: false },
      { x: 31, y: 7, length: 1, isVertical: false },
    ],
    spikes: [
      { x: 14, y: 9, length: 2, isVertical: false, direction: SpikeDirection.UP },
      { x: 21, y: 4, length: 12, isVertical: true, direction: SpikeDirection.RIGHT },
      { x: 23, y: 4, length: 10, isVertical: true, direction: SpikeDirection.LEFT },
      { x: 28, y: 19, length: 14, isVertical: false, direction: SpikeDirection.UP },
      { x: 25, y: 0, length: 8, isVertical: false, direction: SpikeDirection.DOWN },
    ],
    blades: [
      { x1: 12, y1: 11, x2: 12, y2: 13, delay: 200 },
      { x1: 0, y1: 12, x2: 6, y2: 12, delay: 0 },
      { x1: 26, y1: 3, x2: 34, y2: 1, delay: 0 },
    ],
    turrets: [
      { x: 0, y: 0, startDelay: 0 },
    ],
    lasers: [
      { x: 22, y: 17, angle: 0, startDelay: 1000 },
      { x: 25, y: 9, angle: 180, startDelay: 1000 },
    ],
  },
  {
    startGate: { x: 1, y: 17 },
    endGate: { x: 38, y: 1 },
    platforms: [
      { x: 36, y: 4, length: 6, isVertical: false },
      { x: 5, y: 19, length: 7, isVertical: false },
      { x: 5, y: 18, length: 7, isVertical: false },
      { x: 13, y: 19, length: 15, isVertical: false },
      { x: 13, y: 18, length: 11, isVertical: false },
      { x: 6, y: 15, length: 12, isVertical: false },
      { x: 20, y: 11, length: 6, isVertical: true },
      { x: 0, y: 14, length: 8, isVertical: false },
      { x: 7, y: 10, length: 14, isVertical: false },
      { x: 0, y: 10, length: 5, isVertical: false },
      { x: 18, y: 4, length: 6, isVertical: true },
      { x: 19, y: 4, length: 6, isVertical: true },
      { x: 20, y: 4, length: 6, isVertical: true },
      { x: 16, y: 7, length: 3, isVertical: true },
      { x: 17, y: 7, length: 3, isVertical: true },
      { x: 21, y: 16, length: 3, isVertical: false },
      { x: 23, y: 17, length: 1, isVertical: false },
      { x: 24, y: 0, length: 14, isVertical: true },
      { x: 29, y: 15, length: 1, isVertical: false },
      { x: 34, y: 11, length: 1, isVertical: false },
      { x: 31, y: 7, length: 1, isVertical: false },
    ],
    spikes: [
      { x: 14, y: 9, length: 2, isVertical: false, direction: SpikeDirection.UP },
      { x: 21, y: 4, length: 12, isVertical: true, direction: SpikeDirection.RIGHT },
      { x: 23, y: 4, length: 10, isVertical: true, direction: SpikeDirection.LEFT },
      { x: 28, y: 19, length: 14, isVertical: false, direction: SpikeDirection.UP },
      { x: 25, y: 0, length: 8, isVertical: false, direction: SpikeDirection.DOWN },
    ],
    blades: [
      { x1: 10, y1: 11, x2: 10, y2: 13, delay: 400 },
      { x1: 12, y1: 11, x2: 12, y2: 13, delay: 200 },
      { x1: 14, y1: 11, x2: 14, y2: 13, delay: 0 },
      { x1: 0, y1: 12, x2: 6, y2: 12, delay: 0 },
      { x1: 26, y1: 3, x2: 34, y2: 1, delay: 0 },
    ],
    turrets: [
      { x: 0, y: 0, startDelay: 0 },
      { x: 40, y: 17, startDelay: 0 },
    ],
    lasers: [
      { x: 22, y: 17, angle: 0, startDelay: 1000 },
      { x: 25, y: 9, angle: 180, startDelay: 1000 },
    ],
  },
  {
    startGate: { x: 1, y: 17 },
    endGate: { x: 38, y: 1 },
    platforms: [
      { x: 36, y: 4, length: 6, isVertical: false },
      { x: 5, y: 19, length: 7, isVertical: false },
      { x: 5, y: 18, length: 7, isVertical: false },
      { x: 13, y: 19, length: 15, isVertical: false },
      { x: 13, y: 18, length: 11, isVertical: false },
      { x: 6, y: 15, length: 12, isVertical: false },
      { x: 20, y: 11, length: 6, isVertical: true },
      { x: 0, y: 14, length: 8, isVertical: false },
      { x: 7, y: 10, length: 14, isVertical: false },
      { x: 0, y: 10, length: 5, isVertical: false },
      { x: 18, y: 4, length: 6, isVertical: true },
      { x: 19, y: 4, length: 6, isVertical: true },
      { x: 20, y: 4, length: 6, isVertical: true },
      { x: 16, y: 7, length: 3, isVertical: true },
      { x: 17, y: 7, length: 3, isVertical: true },
      { x: 21, y: 16, length: 3, isVertical: false },
      { x: 23, y: 17, length: 1, isVertical: false },
      { x: 24, y: 0, length: 14, isVertical: true },
      { x: 29, y: 15, length: 1, isVertical: false },
      { x: 34, y: 11, length: 1, isVertical: false },
      { x: 31, y: 7, length: 1, isVertical: false },
    ],
    spikes: [
      { x: 4, y: 9, length: 1, isVertical: false, direction: SpikeDirection.UP },
      { x: 7, y: 9, length: 1, isVertical: false, direction: SpikeDirection.UP },
      { x: 14, y: 9, length: 2, isVertical: false, direction: SpikeDirection.UP },
      { x: 21, y: 4, length: 12, isVertical: true, direction: SpikeDirection.RIGHT },
      { x: 23, y: 4, length: 10, isVertical: true, direction: SpikeDirection.LEFT },
      { x: 28, y: 19, length: 14, isVertical: false, direction: SpikeDirection.UP },
      { x: 25, y: 0, length: 8, isVertical: false, direction: SpikeDirection.DOWN },
    ],
    blades: [
      { x1: 10, y1: 11, x2: 10, y2: 13, delay: 400 },
      { x1: 12, y1: 11, x2: 12, y2: 13, delay: 200 },
      { x1: 14, y1: 11, x2: 14, y2: 13, delay: 0 },
      { x1: 0, y1: 12, x2: 6, y2: 12, delay: 0 },
      { x1: 26, y1: 3, x2: 34, y2: 1, delay: 0 },
    ],
    turrets: [
      { x: 0, y: 8, startDelay: 0 },
      { x: 0, y: 0, startDelay: 0 },
      { x: 4, y: 0, startDelay: 1500 },
      { x: 40, y: 17, startDelay: 0 },
    ],
    lasers: [
      { x: 22, y: 17, angle: 0, startDelay: 1000 },
      { x: 41, y: 13, angle: 0, startDelay: 0 },
      { x: 25, y: 9, angle: 180, startDelay: 1000 },
    ],
  },
  {
    startGate: { x: 1, y: 17 },
    endGate: { x: 38, y: 1 },
    platforms: [
      { x: 36, y: 4, length: 6, isVertical: false },
      { x: 5, y: 19, length: 7, isVertical: false },
      { x: 5, y: 18, length: 7, isVertical: false },
      { x: 13, y: 19, length: 15, isVertical: false },
      { x: 13, y: 18, length: 11, isVertical: false },
      { x: 6, y: 15, length: 12, isVertical: false },
      { x: 20, y: 11, length: 6, isVertical: true },
      { x: 0, y: 14, length: 8, isVertical: false },
      { x: 7, y: 10, length: 14, isVertical: false },
      { x: 0, y: 10, length: 5, isVertical: false },
      { x: 18, y: 4, length: 6, isVertical: true },
      { x: 19, y: 4, length: 6, isVertical: true },
      { x: 20, y: 4, length: 6, isVertical: true },
      { x: 16, y: 7, length: 3, isVertical: true },
      { x: 17, y: 7, length: 3, isVertical: true },
      { x: 21, y: 16, length: 3, isVertical: false },
      { x: 23, y: 17, length: 1, isVertical: false },
      { x: 24, y: 0, length: 14, isVertical: true },
      { x: 29, y: 15, length: 1, isVertical: false },
      { x: 34, y: 11, length: 1, isVertical: false },
      { x: 31, y: 7, length: 1, isVertical: false },
    ],
    spikes: [
      { x: 4, y: 9, length: 1, isVertical: false, direction: SpikeDirection.UP },
      { x: 7, y: 9, length: 1, isVertical: false, direction: SpikeDirection.UP },
      { x: 14, y: 9, length: 2, isVertical: false, direction: SpikeDirection.UP },
      { x: 21, y: 4, length: 12, isVertical: true, direction: SpikeDirection.RIGHT },
      { x: 23, y: 4, length: 10, isVertical: true, direction: SpikeDirection.LEFT },
      { x: 28, y: 19, length: 14, isVertical: false, direction: SpikeDirection.UP },
      { x: 25, y: 0, length: 8, isVertical: false, direction: SpikeDirection.DOWN },
    ],
    blades: [
      { x1: 10, y1: 11, x2: 10, y2: 13, delay: 400 },
      { x1: 12, y1: 11, x2: 12, y2: 13, delay: 200 },
      { x1: 14, y1: 11, x2: 14, y2: 13, delay: 0 },
      { x1: 0, y1: 12, x2: 6, y2: 12, delay: 0 },
      { x1: 26, y1: 3, x2: 34, y2: 1, delay: 0 },
    ],
    turrets: [
      { x: 0, y: 15, startDelay: 4000 },
      { x: 18, y: 11, startDelay: 1000 },
      { x: 0, y: 8, startDelay: 0 },
      { x: 0, y: 0, startDelay: 0 },
      { x: 0, y: 4, startDelay: 1500 },
      { x: 4, y: 0, startDelay: 1500 },
      { x: 40, y: 17, startDelay: 0 },
      { x: 40, y: 6, startDelay: 0 },
    ],
    lasers: [
      { x: 22, y: 17, angle: 0, startDelay: 1000 },
      { x: 41, y: 13, angle: 0, startDelay: 0 },
      { x: 25, y: 9, angle: 180, startDelay: 1000 },
    ],
  },

  // New set of levels
  {
    startGate: { x: 1, y: 0 },
    endGate: { x: 38, y: 0 },
    platforms: [
      { x: 12, y: 19, length: 1, isVertical: false },
      { x: 23, y: 19, length: 1, isVertical: false },
      { x: 19, y: 16, length: 4, isVertical: false },
      { x: 37, y: 3, length: 5, isVertical: false },
      { x: 26, y: 12, length: 2, isVertical: false },
      { x: 32, y: 8, length: 1, isVertical: false },
    ],
    blades: [
      { x1: 13, y1: 18, x2: 21, y2: 18, delay: 0 },
    ],
    turrets: [
      { x: 10, y: 0, startDelay: 0 },
    ],
    spikes: [
      { x: 6, y: 19, length: 2, isVertical: false, direction: SpikeDirection.UP },
    ],
    lasers: [
      { x: 31, y: 0, angle: -120, startDelay: 0 },
    ],
  },
  {
    startGate: { x: 1, y: 0 },
    endGate: { x: 38, y: 0 },
    platforms: [
      { x: 12, y: 19, length: 1, isVertical: false },
      { x: 23, y: 19, length: 1, isVertical: false },
      { x: 19, y: 16, length: 4, isVertical: false },
      { x: 37, y: 3, length: 5, isVertical: false },
      { x: 26, y: 12, length: 2, isVertical: false },
      { x: 32, y: 8, length: 1, isVertical: false },
    ],
    blades: [
      { x1: 13, y1: 18, x2: 21, y2: 18, delay: 0 },
      { x1: 29, y1: 2, x2: 29, y2: 12, delay: 0 },
    ],
    turrets: [
      { x: 10, y: 0, startDelay: 0 },
      { x: 17, y: 0, startDelay: 1000 },
    ],
    spikes: [
      { x: 6, y: 19, length: 4, isVertical: false, direction: SpikeDirection.UP },
      { x: 0, y: 4, length: 15, isVertical: true, direction: SpikeDirection.RIGHT },
    ],
    lasers: [
      { x: 31, y: 0, angle: -120, startDelay: 0 },
      { x: 8, y: 0, angle: -75, startDelay: 0 },
    ],
  },
  {
    startGate: { x: 1, y: 0 },
    endGate: { x: 38, y: 0 },
    platforms: [
      { x: 12, y: 19, length: 1, isVertical: false },
      { x: 23, y: 19, length: 1, isVertical: false },
      { x: 19, y: 16, length: 4, isVertical: false },
      { x: 37, y: 3, length: 5, isVertical: false },
      { x: 26, y: 12, length: 2, isVertical: false },
      { x: 32, y: 8, length: 1, isVertical: false },
      { x: 4, y: 9, length: 2, isVertical: false },
      { x: 1, y: 9, length: 1, isVertical: false },
    ],
    blades: [
      { x1: 13, y1: 18, x2: 21, y2: 18, delay: 0 },
      { x1: 29, y1: 2, x2: 29, y2: 12, delay: 0 },
      { x1: 12, y1: 9, x2: 12, y2: 17, delay: 0 },
    ],
    turrets: [
      { x: 10, y: 0, startDelay: 0 },
      { x: 17, y: 0, startDelay: 1000 },
      { x: 40, y: 4, startDelay: 0 },
    ],
    spikes: [
      { x: 6, y: 19, length: 4, isVertical: false, direction: SpikeDirection.UP },
      { x: 0, y: 4, length: 15, isVertical: true, direction: SpikeDirection.RIGHT },
      { x: 0, y: 19, length: 2, isVertical: false, direction: SpikeDirection.UP },
      { x: 3, y: 19, length: 1, isVertical: false, direction: SpikeDirection.UP },
      { x: 28, y: 19, length: 4, isVertical: false, direction: SpikeDirection.UP },
      { x: 34, y: 19, length: 4, isVertical: false, direction: SpikeDirection.UP },
      { x: 40, y: 19, length: 2, isVertical: false, direction: SpikeDirection.UP },
    ],
    lasers: [
      { x: 31, y: 0, angle: -120, startDelay: 0 },
      { x: 8, y: 0, angle: -80, startDelay: 2000 },
      { x: 27, y: 13, angle: 0, startDelay: 0 },
    ],
  },
  {
    startGate: { x: 1, y: 0 },
    endGate: { x: 38, y: 0 },
    platforms: [
      { x: 12, y: 19, length: 1, isVertical: false },
      { x: 23, y: 19, length: 1, isVertical: false },
      { x: 19, y: 16, length: 4, isVertical: false },
      { x: 37, y: 3, length: 5, isVertical: false },
      { x: 26, y: 12, length: 2, isVertical: false },
      { x: 32, y: 8, length: 1, isVertical: false },
      { x: 4, y: 9, length: 2, isVertical: false },
      { x: 1, y: 9, length: 1, isVertical: false },
      { x: 10, y: 13, length: 1, isVertical: false },
    ],
    blades: [
      { x1: 13, y1: 18, x2: 21, y2: 18, delay: 0 },
      { x1: 29, y1: 2, x2: 29, y2: 12, delay: 0 },
      { x1: 12, y1: 9, x2: 12, y2: 17, delay: 0 },
      { x1: 17, y1: 6, x2: 26, y2: 16, delay: 1000 },
    ],
    turrets: [
      { x: 10, y: 0, startDelay: 0 },
      { x: 17, y: 0, startDelay: 1000 },
      { x: 22, y: 0, startDelay: 2000 },
      { x: 40, y: 4, startDelay: 0 },
      { x: 40, y: 16, startDelay: 1000 },
    ],
    spikes: [
      { x: 0, y: 19, length: 12, isVertical: false, direction: SpikeDirection.UP },
      { x: 0, y: 4, length: 15, isVertical: true, direction: SpikeDirection.RIGHT },
      { x: 24, y: 19, length: 18, isVertical: false, direction: SpikeDirection.UP },
    ],
    lasers: [
      { x: 31, y: 0, angle: -120, startDelay: 0 },
      { x: 8, y: 0, angle: -80, startDelay: 2000 },
      { x: 27, y: 13, angle: 0, startDelay: 0 },
      { x: 13, y: 0, angle: -100, startDelay: 0 },
      { x: 41, y: 14, angle: 20, startDelay: 1000 },
    ],
  },
];

export default levels;